# Generated by Django 3.1.3 on 2021-11-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211115_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='branch',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='college',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
